### ISSUE TITLE
'Options' object has no attribute 'cnn_layer_dropout'

### ISSUE THREAD

**Issue by tuvuumass** [dreasysnail/textCNN_public#5]
Hello,

I got the following error when running the code. Could you help solve this issue?

Thanks

Traceback (most recent call last):
  File "demo.py", line 314, in <module>
    main()
  File "demo.py", line 216, in main
    res_, loss_, train_op = auto_encoder(x_, x_org_, opt)
  File "demo.py", line 112, in auto_encoder
    H_enc = conv_model_3layer(x_emb, opt)
  File "model.py", line 237, in conv_model_3layer
    X = regularization(X, opt,  prefix= prefix + 'reg_X', is_reuse= is_reuse, is_train = is_train)
  File "model.py", line 202, in regularization
    X = X if not opt.cnn_layer_dropout else layers.dropout(X, keep_prob = opt.dropout_ratio, scope=prefix + '_dropout')
AttributeError: 'Options' object has no attribute 'cnn_layer_dropout'

**Comment by dreasysnail** [comment]
Hi,

I have updated the code. Please see if this time you are able to run it.

Thanks,

Yizhe

On Feb 19, 2018, 3:21 PM -0500, tuvuumass <notifications@github.com>, wrote:

Hello,

I got the following error when running the code. Could you help solve this issue?

Thanks

Traceback (most recent call last):
File "demo.py", line 314, in
main()
File "demo.py", line 216, in main
res_, loss_, train_op = auto_encoder(x_, x_org_, opt)
File "demo.py", line 112, in auto_encoder
H_enc = conv_model_3layer(x_emb, opt)
File "model.py", line 237, in conv_model_3layer
X = regularization(X, opt, prefix= prefix + 'reg_X', is_reuse= is_reuse, is_train = is_train)
File "model.py", line 202, in regularization
X = X if not opt.cnn_layer_dropout else layers.dropout(X, keep_prob = opt.dropout_ratio, scope=prefix + '_dropout')
AttributeError: 'Options' object has no attribute 'cnn_layer_dropout'

**Comment by tuvuumass** [comment]
It works now! Thanks.
